load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "hydra",
    srcs = ["src/hydra.cpp"],
    hdrs = ["include/hydra.hpp"],
    includes = ["include/"],
    visibility = ["//visibility:public"],
)
